camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputRecordWriter.java
We saw the following exception when we received very old kafka message:
camus-hourly-Lix INFO - task error: Error: java.lang.ClassCastException: org.apache.hadoop.mapred.TaskAttemptContextImpl cannot be cast to org.apache.hadoop.mapreduce.Mapper$Context
18-12-2014 14:16:08 PST camus-hourly-Lix INFO - 	at com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputRecordWriter.write(EtlMultiOutputRecordWriter.java:87)
Actually there is no need to cast TaskAttemptContextImpl to Mapper$Context since TaskAttemptContextImpl have the getCounter method already.
=> Fix the class cast exception in EtlMultiOutputRecordWriter

camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSweeper.java
Currently, when sweeper analyses the source directory tree, it assumes that the first entry inside the topic directory is 1) a directory, 2) the source sub-directory.
Both are not necessarily true.
Assumption 2) fails when destination sub-directory (e.g. 'daily') lexically comes before the source sub-directory (e.g. 'recent'). (This can only happen when source and destination trees are the same.)
Assumption 1) fails under the edge case where additional files are kept in the topic directory (or in any sub-directory). I am storing some topic meta data in the topic directory so this assumption failed for me as well.
This change will make sweeper analyze the entire topic directory and not just the first entry.
=> Sweeper should not depend on the order of directory entries

camus-example/src/main/resources/camus.properties, camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/JsonStringMessageDecoder.java
Allow another special case `camus.message.timestamp.format` value to pipe all timestamps to `org.joda.time.DateTime` constructor (which properly parses [ISO-8601][ISO-8601])
[ISO-8601]: http://www.iso.org/iso/home/standards/iso8601.htm
=> Adding ISO-8601 parsing to JsonStringMessageDecoder

README.md
I think this change may help slightly to reduce our exposure to spam crawlers. There isn't any benefit to exposing the actual email address versus giving the link to subscribe to the group, since we'd like people to register on the group before posting anyway.
The previous text was also slightly messy.
=> Minor clean up of the README's intro.

camus-api/src/main/java/com/linkedin/camus/schemaregistry/CachedSchemaRegistry.java
CachedSchemaRegistry is not using its cache to return the latest schema, it is requesting it everytime instead. This might result in expensive operations. It should ensure it reads from its cache, just like for other schema's requests.
=> CachedSchemaRegistry to get the lastest schema from its cache

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/KafkaReader.java
The pKey object is reused across messages, but is not being reset between each read. #getNext should empty pKey when it receives a message without a partition key.
This is kinda tricky to reproduce in a test :( Any ideas?
=> reset pKey when message#key is null

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputRecordWriter.java
In Hadoop 1, TaskAttemptContext.getCounter() is not available, has to cast context to Mapper.Context
However, in Hadoop 2, TaskAttemptContext becomes an interface, and its implementation, TaskAttemptContextImpl, cannot be cast to Mapper.Context.
Using reflection to make it work for both Hadoop 1 and 2.
Regression test passed on Nertz.
=> Fixed the cast from TaskAttemptContext to Mapper.Context.

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlInputFormat.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/mapred/EtlInputFormatTest.java
Deal with the case when the call to retrieve on topic metadata failed, retry three times.
Added two unit tests for the new behavior (one positive, one negative)
=> ETL-2564: Error handling in camus: Exception on TopicMetadata call

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlInputFormat.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/mapred/EtlInputFormatTest.java
* Refactor EtlInputFormat.getKafkaWhitelistTopic()/getKafkaBlacklistTopic() to simplify testing
* Add a simple test to verify empty entries in whitelists/blacklists are handled correctly. This is important to be able to handle cases like:
kafka.blacklist.topics=${blacklist.topics.A},${blacklist.topics.B}
blacklist.topics.A=
blacklist.topics.B=TopicB1,TopicB2
=> Simple test to verify empty entries in white-/black-lists are handled correctly

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputRecordWriter.java
cache the counter as a static variable "private static Counter topicSkipOldCounter". It is initialized in the constructor of EtlMultiOutputRecordWriter.
=> cache counter in EtlMultiOutputRecordWriter to avoid too many reflections

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/CamusJob.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlInputFormat.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/CamusJobTest.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/CamusJobTestWithMock.java
If unable to fetch latest offset from leader (response==null, response.hasError(), or caught runtime exception), retry three times. If still unable, skip the corresponding topics, proceed with other topics and report job failure.
=> etl2566 - handling offset range call failure

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/CamusJob.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/EtlCounts.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/CamusJobTestWithMock.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/coders/EncoderForUnitTest.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/coders/GenericRecordForUnitTest.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/coders/MonitoringEventForUnitTest.java, camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/common/EtlCountsForUnitTest.java
- Retry if publish count to kafka fails.
- Fail job if max retires reached.
=> Etl2575 - Error handling in camus: publish error

camus-etl-kafka/src/test/java/com/linkedin/camus/etl/kafka/CamusJobTest.java
The after() method in CamusJobTest does not clean up properly, which caused problem for CamusJobTestWithMock.
=> fix unit test

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/EtlCounts.java
Currently job fails if producer.send() fails, but sometimes creating the producer itself may fail, and we should also fail the job in this case.
=> fail job if creating kafka producer failed when sending counds

camus-etl-kafka/build.gradle, camus-sweeper/build.gradle, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusCleaner.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusHourlySweeper.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusHourlySweeperPlanner.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSweeper.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSweeperDatePartitionPlanner.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSweeperMetrics.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSweeperPlanner.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/HiddenFilter.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/mapreduce/CamusSweeperAvroKeyJob.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/utils/DateUtils.java, camus-sweeper/src/test/java/com/linkedin/camus/sweeper/CamusHourlySweeperPlannerTest.java
- Use current daily compaction approach for hourly compaction
- If outliers are detected, rather than reprocess the topic, simply add it to outlier folder
- Refactor the daily compaction code and remove unnecessary logging
- Report per-topic metrics for hourly compaction, such as data size, MR submit time, MR duration, etc.
=> make camus daily compaction work for hourly

camus-api/src/main/java/com/linkedin/camus/coders/Message.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/KafkaMessage.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/KafkaReader.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlRecordReader.java, camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/JsonStringMessageDecoder.java, camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/JsonWrappedStringMessageDecoder.java, camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/KafkaAvroMessageDecoder.java, camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/LatestSchemaKafkaAvroMessageDecoder.java, camus-kafka-coders/src/test/java/com/linkedin/camus/etl/kafka/coders/TestJsonStringMessageDecoder.java, camus-kafka-coders/src/test/java/com/linkedin/camus/etl/kafka/coders/TestMessage.java
We have the requirement within our company to store not only the payload, but also the key, offset, partition, and checksums. So that we can replay the messages exactly as they were read from kafka.
Supplied additional decoder to store the additional data, where payload and key byte data is both json, and wraps this information in a json wrapper returned into the CamusWrapper as String.
Updated other coders, so behaviour for existing remains unchanged.
This is a merge from our internal clone of Camus.
=> Add support to store not only payload

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlRecordReader.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusHourlySweeper.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSingleFolderSweeper.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSingleFolderSweeperPlanner.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSweeper.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/mapreduce/CamusSweeperAvroKeyJob.java, camus-sweeper/src/test/java/com/linkedin/camus/sweeper/CamusSingleFolderSweeperPlannerTest.java
Refactored CamusHourlySweeper, increased flexibility of deduping a single folder (not necessarily a single hourly folder, but any single folder), by add the following properties:
camus.sweeper.always.reprocess
By default, if the dest dir of a table already exists, camus will not process that table. Setting this to true will force reprocess.
camus.sweeper.use.all.attributes
Use all attributes in the schema for deduping.
camus.single.folder.sweeper.folder.structure
Dedup all daily data: */*/*
Dedup all hourly data: */*/*/*
Only dedup daily data in 2015: 2015/*/*
Hourly data in Apr 2015: 2015/04/*/*
And so on
camus.single.folder.sweeper.max.hours.ago (default: 1)
This is another way to control which folder to dedup.
e.g. If you wish to dedup all folders in the past 30 days, set it to 720.
If …
=> Single Folder Compaction

camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSingleFolderSweeper.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/CamusSingleFolderSweeperPlanner.java
Originally the outliers are identifyed by comparing the timestamp of each avro file in the source folder, and the timestamp of the destination folder. If a source file's timestamp > destination folder's timestamp, it means this source file arrived after destination folder was created, and thus it is considered an outlier.
However, an outlier may arrive after the sweeper mappers start, and BEFORE the destination folder is created. Such an outlier will not be processed by the sweeper, and also will not be identified as outliers in the subsequent run, since its timestamp is < destination folder timestamp.
The solution is to write the sweeper MapReduce job start timestamp in the destination folder in a hidden state file, e.g., /data/tracking/PageViewEvent/daily/2015/04/08/_state. This …
=> write mapper start timestamp to destination folder

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/EtlKey.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/KafkaReader.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlInputFormat.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputCommitter.java, camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlRecordReader.java
There were 4 issues in Camus that could cause mapper skew:
-  The biggest one is a bug in calculating avgRecordSize. Camus uses `long`, and calculate the running total size by `currentAvgSize * currentCount`. This is simply wrong. For example, suppose we currently pulled 10000 records, avgSize = 100, so total size = 1million. Then, even if we pull an infinite number of records with size=200 each, the avgRecordSize will still be 100. And if we pull a single record with size < 100, then avgRecordSize will become 99. So, the avgRecordSize will keep decreasing.
The solution is to modify the way the running total size is computed. See `EtlMultiOutputCommitter.addOffset()`.
- There's another bug: say a mapper is responsible for 10 partitions, but it timed out while processing the 5th partition. …
=> Fix camus-hourly mapper skew and improve mapper logging

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/CamusJob.java
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:393)
at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:235)
at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:690)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
at com.linkedin.camus.etl.kafka.CamusJob.main(CamusJob.java:645)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
at …
```
=> Fix for ArrayIndexOutOfBoundsException exception

camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlRecordReader.java
I moved the null check up into the try block. So that exceptions caused by null values are added to maximumDecoderExceptions. Otherwise these exceptions spam the Hadoop logs.
=> Add expections thrown by null values to maximumDecoderExceptions.

camus-sweeper/src/main/java/com/linkedin/camus/sweeper/mapreduce/AvroKeyReducer.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/mapreduce/CamusSweeperOutputCommitter.java, camus-sweeper/src/main/java/com/linkedin/camus/sweeper/utils/RelaxedAvroKeyOutputFormat.java
Currently camus sweeper output files are named part-r-00000.avro etc
Changed to x.y.avro where x = record count in file, y = current timestamp.
=> Use custom output file name that includes record count for Camus sweeper
